[package]
name = "gd32vf103_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-rt = "0.10.0"
panic-halt = "0.2.0"
